apiVersion: v1
data:
  pod: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: entando-jx-nodejs11
      labels:
        jenkins.io/kind: build-pod
      annotations:
        jenkins-x.io/devpodPorts: 9229, 3000, 8080
    spec:
      serviceAccount: jenkins
      nodeSelector:
      volumes:
      - name: workspace-volume
        emptyDir: {}
      - name: docker-daemon
        hostPath:
          path: /var/run/docker.sock
      - name: volume-0
        secret:
          secretName: jenkins-docker-cfg
      containers:
      - name: nodejs
        image: entando/entando-jx-nodejs11:0.0.1
        args:
        - cat
        command:
        - /bin/sh
        - -c
        workingDir: /home/jenkins
        securityContext:
          privileged: true
        tty: true
        env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: sonar.token
        - name: SONAR_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: sonar.github.token
        - name: OWASPDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.username
        - name: OWASPDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.password
        - name: OWASPDB_URL
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.url
        - name: GPG_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.passphrase
        - name: GPG_KEYNAME
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.keyname
        - name: GPG_HOMEDIR
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.homedir
        - name: EXECUTABLE_TYPE
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: executable.type
        - name: ENTANDO_DEFAULT_ROUTING_SUFFIX
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: default.routing.suffix
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: jenkins-x-docker-registry
              key: docker.registry
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2048Mi
        volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - name: docker-daemon
            mountPath: /var/run/docker.sock
          - name: volume-0
            mountPath: /home/jenkins/.docker
kind: ConfigMap
metadata:
  annotations:
    jenkins.io/chart: env
  labels:
    jenkins.io/kind: podTemplate
  name: jenkins-x-pod-template-entando-jx-nodejs
  namespace: jx
