apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        entando-k8s:
          repos:
            entando-jx-maven-java11:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-app-controller:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-app-plugin-link-controller:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-cluster-infrastructure-controller:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-composite-app-controller:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-controller-coordinator:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-custom-model:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-infrastructure-parent:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-keycloak-controller:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-operator-common:
              required_status_checks:
                contexts:
                - pr-build
            entando-k8s-plugin-controller:
              required_status_checks:
                contexts:
                - pr-build
            environment-entando-jx-dev:
              required_status_checks:
                contexts:
                - promotion-build
            environment-entando-jx-production:
              required_status_checks:
                contexts:
                - promotion-build
            environment-entando-jx-staging:
              required_status_checks:
                contexts:
                - promotion-build
      protect-tested-repos: true
    deck:
      spyglass: {}
    gerrit: {}
    owners_dir_blacklist:
      default: null
      repos: null
    plank: 
      job_url_template: https://raw.githubusercontent.com/{{.Spec.Refs.Org}}/devops-results/logs/jenkins-x/logs/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/PR-{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Status.BuildID}}.log
    pod_namespace: jx
    postsubmits:
      entando-k8s/entando-jx-maven-java11:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-app-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-app-plugin-link-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-cluster-infrastructure-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-composite-app-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-controller-coordinator:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-custom-model:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-infrastructure-parent:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-keycloak-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-operator-common:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/entando-k8s-plugin-controller:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
      entando-k8s/environment-entando-jx-dev:
      - agent: tekton
        branches:
        - master
        context: ""
        name: promotion
      entando-k8s/environment-entando-jx-production:
      - agent: tekton
        branches:
        - master
        context: ""
        name: promotion
      entando-k8s/environment-entando-jx-staging:
      - agent: tekton
        branches:
        - master
        context: ""
        name: promotion
    presubmits:
      entando-k8s/entando-jx-maven-java11:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-app-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-app-plugin-link-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-cluster-infrastructure-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-composite-app-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-controller-coordinator:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-custom-model:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-infrastructure-parent:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-keycloak-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-operator-common:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/entando-k8s-plugin-controller:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/environment-entando-jx-dev:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/environment-entando-jx-production:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      entando-k8s/environment-entando-jx-staging:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway: {}
    sinker: {}
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: []
        skip-unknown-contexts: false
      merge_method:
        entando-k8s/entando-jx-maven-java11: merge
        entando-k8s/entando-k8s-app-controller: merge
        entando-k8s/entando-k8s-app-plugin-link-controller: merge
        entando-k8s/entando-k8s-cluster-infrastructure-controller: merge
        entando-k8s/entando-k8s-composite-app-controller: merge
        entando-k8s/entando-k8s-controller-coordinator: merge
        entando-k8s/entando-k8s-custom-model: merge
        entando-k8s/entando-k8s-infrastructure-parent: merge
        entando-k8s/entando-k8s-keycloak-controller: merge
        entando-k8s/entando-k8s-operator-common: merge
        entando-k8s/entando-k8s-plugin-controller: merge
        entando-k8s/environment-entando-jx-dev: merge
        entando-k8s/environment-entando-jx-production: merge
        entando-k8s/environment-entando-jx-staging: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - entando-k8s/entando-jx-maven-java11
        - entando-k8s/entando-k8s-app-controller
        - entando-k8s/entando-k8s-app-plugin-link-controller
        - entando-k8s/entando-k8s-cluster-infrastructure-controller
        - entando-k8s/entando-k8s-composite-app-controller
        - entando-k8s/entando-k8s-controller-coordinator
        - entando-k8s/entando-k8s-custom-model
        - entando-k8s/entando-k8s-infrastructure-parent
        - entando-k8s/entando-k8s-keycloak-controller
        - entando-k8s/entando-k8s-operator-common
        - entando-k8s/entando-k8s-plugin-controller
        - entando-k8s/environment-entando-jx-dev
        - entando-k8s/environment-entando-jx-production
        - entando-k8s/environment-entando-jx-staging
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - entando-k8s/entando-jx-maven-java11
        - entando-k8s/entando-k8s-app-controller
        - entando-k8s/entando-k8s-app-plugin-link-controller
        - entando-k8s/entando-k8s-cluster-infrastructure-controller
        - entando-k8s/entando-k8s-composite-app-controller
        - entando-k8s/entando-k8s-controller-coordinator
        - entando-k8s/entando-k8s-custom-model
        - entando-k8s/entando-k8s-infrastructure-parent
        - entando-k8s/entando-k8s-keycloak-controller
        - entando-k8s/entando-k8s-operator-common
        - entando-k8s/entando-k8s-plugin-controller
        - entando-k8s/environment-entando-jx-dev
        - entando-k8s/environment-entando-jx-production
        - entando-k8s/environment-entando-jx-staging
      target_url: http://deck-jx.apps.serv.run
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-20T08:22:04Z"
  name: config
  namespace: jx
  resourceVersion: "104721137"
  selfLink: /api/v1/namespaces/jx/configmaps/config
  uid: f094bff3-3b5d-11ea-941e-fa163ea775ae
