apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  annotations:
    jenkins.io/chart: env
  labels:
    jenkins.io/chart-release: jenkins-x
    jenkins.io/namespace: jx
    jenkins.io/version: '49'
  name: entando-npm-scheduler
  namespace: jx
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ''
    maxGoroutines: 0
    mergeMethod: merge
    policy:
      fromBranchProtection: true
      optionalContexts: {}
      requiredContexts: {}
      requiredIfPresentContexts: {}
      skipUnknownContexts: false
    prStatusBaseUrl: ''
    squashLabel: ''
    targetUrl: 'http://deck-jx.apps.serv.run'
  plugins:
    entries:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
  policy:
    protectTested: true
  postsubmits:
    entries:
      - agent: tekton
        branches:
          entries:
            - master
        cluster: ''
        context: ''
        labels: {}
        maxConcurrency: 0
        name: release
        report: false
        runIfChanged: '/(?m)^(([^p].*$)|^(p[^a].*$)|^(pa[^c].*$)|^(pac[^k].*$))/gm'
        skipBranches: {}
  presubmits:
    entries:
      - agent: tekton
        alwaysRun: false
        branches: {}
        cluster: ''
        context: pr-build
        labels: {}
        maxConcurrency: 0
        mergeMethod: ''
        name: pr-build
        optional: false
        policy:
          Replace: false
          requiredStatusChecks:
            contexts:
              entries:
                - pr-build
        queries:
          - excludedBranches: {}
            includedBranches: {}
            labels:
              entries:
                - approved
            milestone: ''
            missingLabels:
              entries:
                - do-not-merge
                - do-not-merge/hold
                - do-not-merge/work-in-progress
                - needs-ok-to-test
                - needs-rebase
            reviewApprovedRequired: false
          - excludedBranches: {}
            includedBranches: {}
            labels:
              entries:
                - updatebot
            milestone: ''
            missingLabels:
              entries:
                - do-not-merge
                - do-not-merge/hold
                - do-not-merge/work-in-progress
                - needs-ok-to-test
                - needs-rebase
            reviewApprovedRequired: false
        report: true
        rerunCommand: /test this
        runIfChanged: '/(?m)^(([^p].*$)|^(p[^a].*$)|^(pa[^c].*$)|^(pac[^k].*$))/gm'
        skipBranches: {}
        trigger: '(?m)^/test( all| this),?(\s+|$)'
  schedulerAgent:
    agent: tekton
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ''
    onlyOrgMembers: false
    trustedOrg: entando-k8s
  welcome:
    - message_template: Welcome
