apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: entando
    provider: github
    repository: entando-spring-boot-parent
  name: entando-entando-spring-boot-parent
spec:
  description: Imported application for entando/entando-spring-boot-parent
  httpCloneURL: https://github.com/entando/entando-spring-boot-parent.git
  org: entando
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: entando-spring-boot-parent
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/entando/entando-spring-boot-parent.git
