apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: entando
    provider: github
    repository: app-builder
  name: entando-app-builder
spec:
  description: Imported application for entando/app-builder
  httpCloneURL: https://github.com/entando/app-builder.git
  org: entando
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: app-builder
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/entando/app-builder.git
