adminUser:
  password: local:entando-jx/adminUser:password
  username: admin
docker:
  email: a.barnard@entando.com
  password: local:entando-jx/docker:password
  url: docker-registry.default.svc:5000
  username: admin-entando
enableDocker: true
pipelineUser:
  email: entando.build.user@gmail.com
  token: local:entando-jx/pipelineUser:token
  username: entando-jx
prow:
  hmacToken: local:entando-jx/prow:hmacToken
